In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [7]:
net = nn.Sequential(CenteredLayer())

In [8]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-1.1176e-08)

In [9]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [11]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.4989, -0.6614,  0.2977],
        [ 0.5308, -1.6554, -1.5712],
        [ 0.7426,  1.8555, -0.8844],
        [-0.8650,  0.8800,  2.0096],
        [-3.0166,  1.0738, -1.1740]], requires_grad=True)

In [12]:
linear(torch.rand(2, 5))

tensor([[0.0000, 2.6848, 0.0000],
        [0.0000, 2.3597, 0.0000]])

In [17]:
A = torch.rand(2, 5)
print(A)

tensor([[0.5405, 0.7084, 0.2288, 0.5472, 0.2486],
        [0.1049, 0.0392, 0.0820, 0.5631, 0.8064]])


In [18]:
linear(A)

tensor([[1.0195, 0.9526, 0.0000],
        [0.0000, 2.6888, 0.0345]])

In [19]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[5.2443],
        [8.6471]])